import { Router } from 'express';
import { Authenticate } from '../../middleware/auth.middleware.js';
import * as notificationController from './notification.controller.js';

const router = Router();

/**
 * @swagger
 * tags:
 *   name: Notifications
 *   description: Authenticated notification, push token, and real-time stream APIs
 */

/**
 * @swagger
 * /notifications/token-registration:
 *   post:
 *     summary: Register or update a user FCM token
 *     description: Registers the authenticated user's Firebase Cloud Messaging token for push notifications. If the token already exists, it is reassigned to the current user and its device platform is updated.
 *     tags: [Notifications]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - token
 *               - device_type
 *             properties:
 *               token:
 *                 type: string
 *                 description: Firebase Cloud Messaging registration token generated by the client device.
 *                 example: dFcmToken_abc123xyz
 *               device_type:
 *                 type: string
 *                 enum: [android, ios, web]
 *                 description: Platform that owns the FCM token.
 *                 example: web
 *     responses:
 *       200:
 *         description: Token registered or updated successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: Token registered successfully
 *       400:
 *         description: Missing token, missing device type, or unsupported device platform.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: Device type must be one of android, ios, web
 *       401:
 *         description: Authentication token is missing or invalid.
 */
router.post('/token-registration', Authenticate, notificationController.registerToken);

/**
 * @swagger
 * /notifications:
 *   get:
 *     summary: Get notifications for the authenticated user
 *     description: Returns a paginated list of notifications assigned to the authenticated user, ordered from newest to oldest. Optionally filters by notification type.
 *     tags: [Notifications]
 *     security:
 *       - bearerAuth: []
 *     parameters:
 *       - in: query
 *         name: page
 *         schema:
 *           type: integer
 *           minimum: 1
 *           default: 1
 *         required: false
 *         description: Page number to retrieve.
 *         example: 1
 *       - in: query
 *         name: limit
 *         schema:
 *           type: integer
 *           minimum: 1
 *           default: 10
 *         required: false
 *         description: Number of notifications returned per page.
 *         example: 10
 *       - in: query
 *         name: type
 *         schema:
 *           type: string
 *           enum: [order, payment, promotion, system]
 *         required: false
 *         description: Filter notifications by type.
 *         example: order
 *     responses:
 *       200:
 *         description: Notifications returned successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 data:
 *                   type: object
 *                   properties:
 *                     notifications:
 *                       type: array
 *                       items:
 *                         type: object
 *                         properties:
 *                           id:
 *                             type: integer
 *                             example: 12
 *                           title:
 *                             type: string
 *                             example: Đơn hàng đã được giao
 *                           body:
 *                             type: string
 *                             example: Đơn hàng #123 của bạn đã được giao thành công.
 *                           type:
 *                             type: string
 *                             enum: [order, payment, promotion, system]
 *                             example: order
 *                           metadata:
 *                             type: object
 *                             nullable: true
 *                             additionalProperties: true
 *                             example:
 *                               orderId: 123
 *                               status: delivered
 *                           created_at:
 *                             type: string
 *                             format: date-time
 *                             example: 2026-05-24T10:30:00.000Z
 *                           user_notifications:
 *                             type: array
 *                             description: Read state for the authenticated user.
 *                             items:
 *                               type: object
 *                               properties:
 *                                 is_read:
 *                                   type: boolean
 *                                   example: false
 *                                 read_at:
 *                                   type: string
 *                                   format: date-time
 *                                   nullable: true
 *                                   example: null
 *                 pagination:
 *                   type: object
 *                   properties:
 *                     total:
 *                       type: integer
 *                       example: 25
 *                     page:
 *                       type: integer
 *                       example: 1
 *                     limit:
 *                       type: integer
 *                       example: 10
 *                     hasMore:
 *                       type: boolean
 *                       example: true
 *       400:
 *         description: Invalid notification type.
 *       401:
 *         description: Authentication token is missing or invalid.
 */
router.get('/', Authenticate, notificationController.getNotifications);

/**
 * @swagger
 * /notifications/unread-count:
 *   get:
 *     summary: Get unread notification count
 *     description: Returns the number of unread notifications assigned to the authenticated user.
 *     tags: [Notifications]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: Unread notification count returned successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 count:
 *                   type: integer
 *                   description: Number of unread notifications for the authenticated user.
 *                   example: 3
 *       401:
 *         description: Authentication token is missing or invalid.
 */
router.get('/unread-count', Authenticate, notificationController.getUnreadCount);

/**
 * @swagger
 * /notifications/stream:
 *   get:
 *     summary: Stream notifications with Server-Sent Events
 *     description: Opens a Server-Sent Events connection for the authenticated user. The API marks the user as online, pushes each notification as a `data:` event containing a JSON string, refreshes online status while connected, and marks the user offline when the connection closes.
 *     tags: [Notifications]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: 'SSE stream opened successfully. Each event is sent as `data: {json}\n\n`.'
 *         content:
 *           text/event-stream:
 *             schema:
 *               type: string
 *               example: "data: {\"id\":12,\"title\":\"Đơn hàng đã được giao\",\"body\":\"Đơn hàng #123 của bạn đã được giao thành công.\",\"type\":\"order\",\"metadata\":{\"orderId\":123,\"status\":\"delivered\"},\"created_at\":\"2026-05-24T10:30:00.000Z\"}\n\n"
 *       401:
 *         description: Authentication token is missing or invalid.
 *       500:
 *         description: Error while opening or maintaining the notification stream.
 */
router.get('/stream', Authenticate, notificationController.streamNotifications);

/**
 * @swagger
 * /notifications/mark-as-read:
 *   post:
 *     summary: Mark selected notifications as read
 *     description: Marks the authenticated user's notification records as read for the provided notification IDs. IDs that do not belong to the user are ignored by the update.
 *     tags: [Notifications]
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: false
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               notificationIds:
 *                 type: array
 *                 description: Notification IDs to mark as read. If omitted, the API returns a success message without updating anything.
 *                 items:
 *                   type: integer
 *                 example: [12, 13, 14]
 *     responses:
 *       200:
 *         description: Notifications were marked as read, or no notification IDs were provided.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   examples:
 *                     marked:
 *                       value: Notifications marked as read successfully
 *                     noNotifications:
 *                       value: No notifications to mark as read
 *       400:
 *         description: notificationIds is present but is not an array.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: Notification IDs must be an array
 *       401:
 *         description: Authentication token is missing or invalid.
 */
router.post('/mark-as-read', Authenticate, notificationController.markAsRead);

/**
 * @swagger
 * /notifications/mark-all-as-read:
 *   post:
 *     summary: Mark all notifications as read
 *     description: Marks every unread notification assigned to the authenticated user as read and sets each read timestamp to the current server time.
 *     tags: [Notifications]
 *     security:
 *       - bearerAuth: []
 *     responses:
 *       200:
 *         description: All unread notifications were marked as read.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: All notifications marked as read successfully
 *       401:
 *         description: Authentication token is missing or invalid.
 */
router.post('/mark-all-as-read', Authenticate, notificationController.markAllAsRead);

export default router;
